### ISSUE TITLE
[Feature Request]support pac file

### ISSUE THREAD

**Issue by XenoAmess** [trojan-gfw/trojan#421] opened 2020-05-12 05:34 UTC
as title.
suggest support pac file format like ss did.

**Comment by oasiscifr** [comment] 2020-05-12 06:48
@XenoAmess Why

**Comment by XenoAmess** [comment] 2020-05-12 07:24
> @XenoAmess Why

because useful.

**Comment by tomac4t** [comment] 2020-05-12 08:13
Duplicate of #54

**Comment by wongsyrone** [comment] 2020-05-12 08:28
https://github.com/trojan-gfw/trojan/pull/54#issuecomment-453370302

**Closed as completed by wongsyrone** 2020-05-12 08:28 UTC
Labels: enhancement
