### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by tanpengsccd** [trojan-gfw/trojan#383] opened 2020-04-08 06:06 UTC
I want trojan server to handle muti  host  with muti cert  at 443 port.
like caddy config:
```
www.h6.work
{
  tls tanpengcd@gmail.com 
  proxy /home localhost:20080 {
        websocket
        header_upstream -Origin
  }
}

www.h6.work
{
tls tanpengcd@gmail.com 
  proxy / localhost:6000 {
        transparent
  }
}
```
how can I config  server?

**Comment by GreaterFire** [comment] 2020-04-08 06:17
Duplicate of #131

**Closed as completed by GreaterFire** 2020-04-08 06:17 UTC
Labels: bug
