### ISSUE TITLE
About Trojan Server speed limit feature

### ISSUE THREAD

**Issue by Ops-online** [trojan-gfw/trojan#241] opened 2020-02-07 02:46 UTC
Hello!
I saw in Trojan-panel, Trojan Server quota Trojan Client upload and download capacity. So, is there a limit on upload and download speeds for Trojan Client?
If not, do you consider adding this feature in a future release?

**Comment by GreaterFire** [comment] 2020-02-07 02:48
@blueskyxu Duplicate of #195

**Comment by Ops-online** [comment] 2020-02-07 02:58
Thanks

**Closed as completed** 2020-02-07 02:59 UTC
Labels: enhancement
