### ISSUE TITLE
[Feature Request] Add torjan to Homebrew

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#147] opened 2019-10-12 10:44 UTC
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

Hi, Can you add torjan package to Homebrew please? Thanks

**Comment by cattyhouse** [comment] 2019-10-12 13:53
here is a trick to download latest trojan for macOS
````
cd ~ && curl -sOL https://github.com$(curl -sL https://github.com/trojan-gfw/trojan/releases | grep macos | head -n1 | cut -d '"' -f2)
````
then you can do more such as unzip, mv, rm...

**Comment by GreaterFire** [comment] 2019-10-12 17:49
Duplicate of https://github.com/trojan-gfw/homebrew-trojan/issues/2

**Comment by GreaterFire** [comment] 2019-10-12 17:49
Please refer to the discussions there. Thanks!

**Closed as completed** 2019-10-12 17:49 UTC
Labels: duplicate, enhancement
