### ISSUE TITLE
can add thread pool

### ISSUE THREAD

**Issue by jhb92** [trojan-gfw/trojan#220] opened 2020-01-18 12:36 UTC
i want to add thread pool feature, add code as follow in main.cpp file. is it ok?

const unsigned intDEFAULT_THREAD_POOL_SIZE = 2;

unsigned intthread_pool_size =      std::thread::hardware_concurrency() * 2;           
if (thread_pool_size == 0)       thread_pool_size=DEFAULT_THREAD_POOL_SIZE;

for ( int i = 0; i < thread_pool_size;++i)     
     boost::thread( run_service);   

void run_service() {   service.run(); }

**Comment by jhb92** [comment] 2020-01-18 14:12
sorry,above is wrong. here is my thread pool code,test on my machine,please check it.

**service.h** 
add public method.
public:
    void run_service();

**service.cpp**
#include <thread>
const unsigned int DEFAULT_THREAD_POOL_SIZE = 2;
void Service::run_service() {
    unsigned int thread_pool_size = std::thread::hardware_concurrency() * 2;
    if (thread_pool_size == 0)
        thread_pool_size=DEFAULT_THREAD_POOL_SIZE;

    std::vector<std::thread> vecOfThreads;
    for (unsigned int i = 0; i < thread_pool_size;++i)
        vecOfThreads.push_back(std::thread([this]() {
            this->run();
            auto tid = std::this_thread::get_id();
            stringstream ss;
            ss << tid;
            Log::log_with_date_time("From Thread ID : "+ ss.str() , Log::INFO);
        }));

    for (std::thread & th : vecOfThreads)
    {
        if (th.joinable())
            th.join();
    }
}

**main.cpp**
change service.run() to  service.run_service()

**Comment by xyanrch** [comment] 2020-01-19 00:19
https://github.com/trojan-gfw/trojan/pull/179 maybe this link will behelpful for you·

**Comment by GreaterFire** [comment] 2020-01-25 08:58
Duplicate of #179

**Closed as completed by GreaterFire** 2020-01-25 08:58 UTC
Labels: duplicate
